### ISSUE TITLE
Building app on android 12 api 31 fails

### ISSUE THREAD

**Issue by Fanatic6** [evilrat/flutter_zoom_sdk#72]
adb: failed to install /Users/support/Development/tadrees/code/mobile/edforce/build/app/outputs/flutter-apk/app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl744504172.tmp/base.apk (at Binary XML file line #128): com.evilratt.flutter_zoom_sdk.CustomWaitActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error running application on sdk gphone64 x86 64.

I believe you have to add the android:exporte"true" to your androidmanifest

**Comment by Fanatic6** [comment]
Fixed it by adding the line in your androidmanifest. Though i think you should add it in there permanently

**Comment by tinyCoder32** [comment]
Got the same thing here, the error has gone after adding `android:exported="false"` to the `activity` element in the manifest file a `~/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zoom_sdk-1.1.0+3/android/src/main`.

**Comment by Manojdaiya1992** [comment]
Hi @tinyCoder32 @Fanatic6 @evilrat 

This is my AndroidManifest.xml file under flutter_zoom_sdk/android/src/main

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.evilratt.flutter_zoom_sdk">

    <application>
        <activity android:name=".CustomWaitActivity" android:exported="false">
            <intent-filter>
                <action android:name="com.evilratt.flutter_zoom_sdk.intent.action.JoinBeforeHost" />
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
        </activity>
    </application>
</manifest>


But I still got the error when I run it on android 31 SDK getting the below error. Please help.
I also tried with android:exported="true" but got the same error


 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(13075): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(13075):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
E/AndroidRuntime(13075):        at android.app.ActivityThread.access$1700(ActivityThread.java:247)
E/AndroidRuntime(13075):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
E/AndroidRuntime(13075):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13075):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13075):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13075):        at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(13075):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13075):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13075):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(13075): Caused by: java.lang.IllegalArgumentException: com.nrichlearning.nrichmobile: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(13075): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(13075):        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(13075):        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
E/AndroidRuntime(13075):        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
E/AndroidRuntime(13075):        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
E/AndroidRuntime(13075):        at us.zoom.sdk.SDKNotificationMgr.showConfNotificationForSDK(SDKNotificationMgr.java:10)
E/AndroidRuntime(13075):        at com.zipow.videobox.share.ScreenShareServiceForSDK.onCreate(ScreenShareServiceForSDK.java:3)
E/AndroidRuntime(13075):        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
